"""
With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............
Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........
Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
....^|^...^....
.....|.........
...^.^|..^.^...
......|........
..^..|^.....^..
.....|.........
.^.^.^|^.^...^.
......|........
In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?
"""

import os


def solution():
    input_path = os.path.join(os.path.dirname(__file__), "input.txt")
    with open(input_path) as f:
        grid = [line.rstrip("\n") for line in f if line.rstrip("\n") != ""]

    if not grid:
        return 0

    rows = len(grid)
    cols = len(grid[0])

    # Find the starting position.
    s_row = s_col = None
    for r, line in enumerate(grid):
        if "S" in line:
            s_row = r
            s_col = line.index("S")
            break
    if s_row is None:
        return 0

    active = {s_col: 1}  # column -> number of timelines at current row
    finished = 0

    for r in range(s_row + 1, rows):
        row = grid[r]
        next_active = {}
        for c, count in active.items():
            if c < 0 or c >= cols:
                finished += count
                continue
            cell = row[c]
            if cell == "^":
                # Split into left and right.
                left = c - 1
                right = c + 1
                if left < 0:
                    finished += count
                else:
                    next_active[left] = next_active.get(left, 0) + count
                if right >= cols:
                    finished += count
                else:
                    next_active[right] = next_active.get(right, 0) + count
            else:
                next_active[c] = next_active.get(c, 0) + count
        active = next_active
        if not active:
            break

    # Any timelines still active exit the manifold downward.
    finished += sum(active.values())

    return finished


if __name__ == "__main__":
    print(solution())
